[package]
authors = ["Magnus Bergmark <magnus.bergmark@gmail.com>"]
name = "mpris"
version = "0.1.0"

[dependencies]
error-chain = "0.11.0"

[dependencies.dbus]
git = "https://github.com/diwic/dbus-rs.git"
